# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: 永湃科技
        password: wu5zhong2yu1
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy docker://docker.io/golang:alpine docker://registry.cn-hangzhou.aliyuncs.com/wuzhongyu/golang:alpine
        skopeo copy docker://docker.io/alpine:latest docker://registry.cn-hangzhou.aliyuncs.com/wuzhongyu/alpine:latest
        skopeo copy docker://docker.io/node:16 docker://registry.cn-hangzhou.aliyuncs.com/wuzhongyu/node:16
        skopeo copy docker://docker.io/node:18 docker://registry.cn-hangzhou.aliyuncs.com/wuzhongyu/node:18
        skopeo copy docker://docker.io/nginx:alpine docker://registry.cn-hangzhou.aliyuncs.com/wuzhongyu/nginx:alpine
 
